# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, pkgs-unstable, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # [[ NETWORKING ]] {{{
  networking.networkmanager.enable = true; # Enable networking
  networking.hostName = "hp-laptop"; # Define your hostname.

  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

  # }}}

  # [[ TIME ZONE & LOCALE ]] {{{
  # Set your time zone.
  time.timeZone = "Europe/Oslo";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_GB.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "nb_NO.UTF-8";
    LC_IDENTIFICATION = "nb_NO.UTF-8";
    LC_MEASUREMENT = "nb_NO.UTF-8";
    LC_MONETARY = "nb_NO.UTF-8";
    LC_NAME = "nb_NO.UTF-8";
    LC_NUMERIC = "nb_NO.UTF-8";
    LC_PAPER = "nb_NO.UTF-8";
    LC_TELEPHONE = "nb_NO.UTF-8";
    LC_TIME = "nb_NO.UTF-8";
  };
  # }}}

  # # [[ INPUT METHOD / fcitx5 ]]
  # # TODO: Figure out how to use fcitx5 without ruining my current xkb setup.
  # # fcitx5 is probably very cool, but it has weird conflicts with ctrl:swapcaps
  # # that i have not yet figured out...
  # i18n.inputMethod = { # {{{
  #   type = "fcitx5";
  #   enable = true;
  #   fcitx5.addons = with pkgs; [
  #     fcitx5-mozc
  #     fcitx5-gtk
  #   ];
  #   # To suppress warnings about env vars on wayland
  #   fcitx5.waylandFrontend = true;
  # };
  # # }}}

  # [[ CONFIGURE CONSOLE (i.e. tty) ]] {{{
  console = {
    earlySetup = true;
    font = "${pkgs.terminus_font}/share/consolefonts/ter-132n.psf.gz";
    packages = with pkgs; [ terminus_font ];
    keyMap = "no";
  }; # }}}

  users.users.emilio = { # {{{
    isNormalUser = true;
    description = "Emilio Lombardo";
    extraGroups = [ "networkmanager" "wheel" ];
    shell = pkgs.zsh;
    packages = with pkgs; [
      # TODO: Move terminal utils without user config from home.nix to here
      nh
      nix-output-monitor
    ];
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE2x/XJb4aWJdnd+vWz7biG0PXXAnN1FR9wOiocG0Rix emilomb3@gmail.com"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOcEkos+BmHJWg8gelAaa9QQ6rFO+bhUn9388Fk+RV/o Generated By Termius"
    ];
    # Don't forget to set a password with ‘passwd’.
  }; # }}}

  # [[ PROGRAMS ]] {{{

  programs.zsh.enable = true;

  programs.git = {
    enable = true;
    config = {
      push.autoSetupRemote = true;
      credential.helper = "${
          pkgs.git.override { withLibsecret = true; }
        }/bin/git-credential-libsecret";
    };
  };

  nixpkgs = {
    # Allow unfree packages
    config.allowUnfree = true;
    overlays = [
      (final: prev: {
        unstable = pkgs-unstable;
      })
    ];
  };

  # List packages installed in system profile. To search, run:
  # $ nix search wget
  environment.systemPackages = with pkgs; [
    vim
    neovim
  #  unstable.hello
  #  wget
  ];

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
  # programs.mtr.enable = true;
  programs.gnupg.agent = {
    enable = true;
    enableSSHSupport = true;
  };

  # Enable mosh, the ssh alternative when client has bad connection
  # Opens UDP ports 60000 ... 61000
  programs.mosh.enable = true;
  
  # }}}

  # [[ SERVICES ]] {{{

  # Enable the OpenSSH daemon.
  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = false;
      KbdInteractiveAuthentication = false;
      PermitRootLogin = "no";
      AllowUsers = [ "emilio" ];
    };
  };

  services.tailscale.enable = true;

  # }}}

  environment.sessionVariables = {
    NH_OS_FLAKE = "/etc/nixos";
  };

  # Add symlinks in /bin for bash and zsh so that the usual script hashbangs work
  system.activationScripts.binbash = {
    deps = [ "binsh" ];
    text = ''
         ln -sf ${pkgs.zsh}/bin/zsh /bin/zsh
         ln -sfL /bin/sh /bin/bash
    '';
  };

  # Enable swap file
  swapDevices = [{
    device = "/var/lib/swapfile";
    size = 2*1024; # 2 GB
  }];

  # Open ports in the firewall.
  # networking.firewall.allowedTCPPorts = [ ... ];
  # networking.firewall.allowedUDPPorts = [ ... ];
  # Or disable the firewall altogether.
  # networking.firewall.enable = false;

  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "25.05"; # Did you read the comment?

}

# vim: foldmethod=marker sw=2
